import { CalendarEvent, EventCategoryFilter } from '@/types';

export const eventCategoryFilters: EventCategoryFilter[] = [
  { id: 'all', label: '전체', emoji: '📅' },
  { id: 'institution', label: '경제지표', emoji: '🏛️' },
  { id: 'earnings', label: '실적발표', emoji: '📊' },
  { id: 'corporate', label: '기업이벤트', emoji: '🎉' },
  { id: 'crypto', label: '암호화폐', emoji: '🪙' },
];

export const calendarEvents: CalendarEvent[] = [
  // 1월
  {
    id: 'tsla-4q-2023',
    date: '2024-01-24',
    title: 'Tesla 4Q 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'fomc-jan-2024',
    date: '2024-01-31',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'aapl-1q-2024',
    date: '2024-01-30',
    title: 'Apple 1Q 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'samsung-4q-2023',
    date: '2024-01-31',
    title: '삼성전자 4Q 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2023년 4분기 실적 발표',
  },
  // 2월
  {
    id: 'nvda-4q-2023',
    date: '2024-02-21',
    title: 'NVIDIA 4Q 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2023년 4분기 실적 발표',
  },
  {
    id: 'us-cpi-feb-2024',
    date: '2024-02-13',
    title: '미국 CPI 발표',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '22:30',
    description: '1월 소비자물가지수',
  },
  // 3월
  {
    id: 'fomc-mar-2024',
    date: '2024-03-20',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'eth-dencun',
    date: '2024-03-13',
    title: '이더리움 덴쿤 업그레이드',
    category: 'crypto',
    companyDomain: 'ethereum.org',
    importance: 'high',
    description: 'Proto-danksharding 도입',
  },
  // 4월
  {
    id: 'tsla-1q-2024',
    date: '2024-04-17',
    title: 'Tesla 1Q 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  {
    id: 'btc-halving',
    date: '2024-04-19',
    title: '비트코인 반감기',
    category: 'crypto',
    companyDomain: 'bitcoin.org',
    importance: 'high',
    time: '04:00',
    description: '채굴 보상 6.25 → 3.125 BTC로 감소',
  },
  {
    id: 'samsung-1q-2024',
    date: '2024-04-26',
    title: '삼성전자 1Q 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 1분기 실적 발표',
  },
  // 5월
  {
    id: 'fomc-may-2024',
    date: '2024-05-01',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'aapl-2q-2024',
    date: '2024-05-02',
    title: 'Apple 2Q 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'nvda-1q-2024',
    date: '2024-05-22',
    title: 'NVIDIA 1Q 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 1분기 실적 발표',
  },
  // 6월
  {
    id: 'apple-wwdc-2024',
    date: '2024-06-10',
    title: 'Apple WWDC 2024',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'Apple 개발자 컨퍼런스',
  },
  {
    id: 'fomc-jun-2024',
    date: '2024-06-12',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  // 7월
  {
    id: 'samsung-unpacked-jul-2024',
    date: '2024-07-10',
    title: '삼성 갤럭시 언팩',
    category: 'corporate',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '23:00',
    description: 'Galaxy Z Fold6, Z Flip6 공개',
  },
  {
    id: 'tsla-2q-2024',
    date: '2024-07-23',
    title: 'Tesla 2Q 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  {
    id: 'fomc-jul-2024',
    date: '2024-07-31',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'samsung-2q-2024',
    date: '2024-07-31',
    title: '삼성전자 2Q 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 2분기 실적 발표',
  },
  // 8월
  {
    id: 'aapl-3q-2024',
    date: '2024-08-01',
    title: 'Apple 3Q 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'nvda-2q-2024',
    date: '2024-08-28',
    title: 'NVIDIA 2Q 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 2분기 실적 발표',
  },
  // 9월
  {
    id: 'apple-iphone16-event',
    date: '2024-09-09',
    title: 'Apple 아이폰 16 이벤트',
    category: 'corporate',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '02:00',
    description: 'iPhone 16 시리즈 공개',
  },
  {
    id: 'fomc-sep-2024',
    date: '2024-09-18',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  // 10월
  {
    id: 'tsla-3q-2024',
    date: '2024-10-23',
    title: 'Tesla 3Q 실적발표',
    category: 'earnings',
    companyDomain: 'tesla.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  {
    id: 'aapl-4q-2024',
    date: '2024-10-30',
    title: 'Apple 4Q 실적발표',
    category: 'earnings',
    companyDomain: 'apple.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 4분기 실적 발표',
  },
  {
    id: 'samsung-3q-2024',
    date: '2024-10-31',
    title: '삼성전자 3Q 실적발표',
    category: 'earnings',
    companyDomain: 'samsung.com',
    importance: 'high',
    time: '09:00',
    description: '2024년 3분기 실적 발표',
  },
  // 11월
  {
    id: 'fomc-nov-2024',
    date: '2024-11-07',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
  {
    id: 'nvda-3q-2024',
    date: '2024-11-20',
    title: 'NVIDIA 3Q 실적발표',
    category: 'earnings',
    companyDomain: 'nvidia.com',
    importance: 'high',
    time: '06:00',
    description: '2024년 3분기 실적 발표',
  },
  // 12월
  {
    id: 'fomc-dec-2024',
    date: '2024-12-18',
    title: 'FOMC 금리 결정',
    category: 'institution',
    countryCode: 'us',
    importance: 'high',
    time: '04:00',
    description: '연준 기준금리 결정',
  },
];
