import { NewsItem } from '@/types';

export const newsData: NewsItem[] = [
  {
    id: 1,
    category: "정보",
    categoryIcon: "info",
    source: "WSJ",
    time: "3시간 전",
    title: "연준, 2024년 금리 인하 가능성 시사... 시장 기대감 상승",
    tags: ["#연준", "#금리"],
    summary: "제롬 파월 연준 의장이 인플레이션이 목표치에 근접하고 있다며 내년 금리 인하 가능성을 시사했다. 이에 따라 미국 증시는 일제히 상승 마감했으며, 특히 기술주 중심의 나스닥이 강세를 보였다.",
    likes: 43,
    comments: 47,
    upvotes: 206,
    downvotes: 35,
    views: 1247,
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=338&fit=crop",
    companyDomain: "federalreserve.gov",
  },
  {
    id: 2,
    category: "속보",
    categoryIcon: "breaking",
    source: "Bloomberg",
    time: "5시간 전",
    title: "테슬라, 중국 상하이 공장 증설 발표... 연간 생산량 100만대 목표",
    tags: ["#테슬라", "#중국"],
    summary: "테슬라가 상하이 기가팩토리의 생산 능력을 대폭 확대한다고 발표했다. 이번 증설로 연간 생산량이 기존 75만대에서 100만대로 증가할 전망이다.",
    likes: 128,
    comments: 89,
    upvotes: 445,
    downvotes: 23,
    views: 3892,
    imageUrl: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=600&h=338&fit=crop",
    companyDomain: "tesla.com",
  },
  {
    id: 3,
    category: "분석",
    categoryIcon: "analysis",
    source: "Reuters",
    time: "8시간 전",
    title: "엔비디아 실적 분석: AI 칩 수요 폭발로 예상치 상회",
    tags: ["#엔비디아", "#AI", "#실적"],
    summary: "엔비디아가 3분기 실적을 발표했다. 매출은 전년 동기 대비 206% 증가한 181억 달러를 기록했으며, 이는 시장 예상치를 크게 상회하는 수치다. 데이터센터 부문이 성장을 견인했다.",
    likes: 256,
    comments: 134,
    upvotes: 892,
    downvotes: 45,
    views: 8234,
    imageUrl: "https://images.unsplash.com/photo-1639322537228-f710d846310a?w=600&h=338&fit=crop",
    companyDomain: "nvidia.com",
  },
  {
    id: 4,
    category: "암호화폐",
    categoryIcon: "crypto",
    source: "CoinDesk",
    time: "12시간 전",
    title: "비트코인 ETF 승인 임박... SEC 최종 결정 D-7",
    tags: ["#비트코인", "#ETF", "#SEC"],
    summary: "미국 증권거래위원회(SEC)가 비트코인 현물 ETF 승인을 앞두고 있다. 블랙록, 피델리티 등 대형 자산운용사들의 신청이 잇따르면서 시장의 기대감이 고조되고 있다.",
    likes: 312,
    comments: 198,
    upvotes: 1024,
    downvotes: 67,
    views: 12453,
    imageUrl: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=600&h=338&fit=crop",
    companyDomain: "bitcoin.org",
  },
  {
    id: 5,
    category: "경제지표",
    categoryIcon: "economic",
    source: "CNBC",
    time: "1일 전",
    title: "미국 고용지표 예상 상회... 실업률 3.7% 유지",
    tags: ["#고용", "#미국경제"],
    summary: "미국 노동부가 발표한 12월 고용보고서에 따르면 비농업 부문 신규 고용은 21만 6천명을 기록해 시장 예상치 17만명을 상회했다. 실업률은 3.7%로 전월과 동일하게 유지됐다.",
    likes: 89,
    comments: 56,
    upvotes: 334,
    downvotes: 28,
    views: 4521,
    imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=338&fit=crop",
    companyDomain: "dol.gov",
  },
  {
    id: 6,
    category: "속보",
    categoryIcon: "breaking",
    source: "Reuters",
    time: "2일 전",
    title: "애플, 비전 프로 출시 임박... AR/VR 시장 판도 변화 예고",
    tags: ["#애플", "#비전프로", "#AR"],
    summary: "애플이 첫 번째 혼합현실 헤드셋 '비전 프로'의 출시를 앞두고 있다. 3,499달러의 고가 정책에도 불구하고 업계에서는 AR/VR 시장의 새로운 전환점이 될 것으로 전망하고 있다.",
    likes: 234,
    comments: 156,
    upvotes: 678,
    downvotes: 34,
    views: 9823,
    imageUrl: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=600&h=338&fit=crop",
    companyDomain: "apple.com",
  },
  {
    id: 7,
    category: "분석",
    categoryIcon: "analysis",
    source: "Bloomberg",
    time: "2일 전",
    title: "2024년 글로벌 경제 전망: 연착륙 가능성과 리스크 요인",
    tags: ["#글로벌경제", "#2024전망"],
    summary: "주요 투자은행들이 2024년 경제 전망을 발표했다. 대부분 연착륙 시나리오를 예상하지만, 지정학적 리스크와 인플레이션 재발 가능성을 주요 변수로 꼽고 있다.",
    likes: 178,
    comments: 89,
    upvotes: 445,
    downvotes: 23,
    views: 6721,
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&h=338&fit=crop",
    companyDomain: "imf.org",
  },
  {
    id: 8,
    category: "암호화폐",
    categoryIcon: "crypto",
    source: "CoinDesk",
    time: "3일 전",
    title: "이더리움 덴쿤 업그레이드, 레이어2 수수료 90% 절감 기대",
    tags: ["#이더리움", "#덴쿤", "#레이어2"],
    summary: "이더리움 네트워크의 대규모 업그레이드인 '덴쿤'이 예정대로 진행될 전망이다. 이번 업그레이드로 레이어2 솔루션의 거래 수수료가 최대 90%까지 절감될 것으로 예상된다.",
    likes: 445,
    comments: 234,
    upvotes: 1234,
    downvotes: 56,
    views: 15678,
    imageUrl: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=600&h=338&fit=crop",
    companyDomain: "ethereum.org",
  },
];
